/*
 * IS 303 Project 2
 * Author: Andy Mockler
 * Date: March 13, 2015
 * Description: GUI Pre-req GPA Calculator. On run, shows a form used to
 *              calculate a student's overall pre-requisite GPA for the IS
 *              program. Displays green, yellow, or red indicator depending on 
 *              how high the student's GPA is.
 */

import java.text.DecimalFormat;


public class project2 extends javax.swing.JFrame {

    // For formatting GPA as X.XX
    DecimalFormat decimalFormat = new DecimalFormat("0.00");
    
    /**
     * Creates new form project2
     */
    public project2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        pnlGrades = new javax.swing.JPanel();
        lblEnterGrades = new javax.swing.JLabel();
        labelIS100 = new javax.swing.JLabel();
        labelIS102 = new javax.swing.JLabel();
        labelIS201 = new javax.swing.JLabel();
        labelIS303 = new javax.swing.JLabel();
        labelACC200 = new javax.swing.JLabel();
        labelFIN201 = new javax.swing.JLabel();
        labelBUSM241 = new javax.swing.JLabel();
        creditsIS201 = new javax.swing.JTextField();
        creditsIS100 = new javax.swing.JTextField();
        creditsIS102 = new javax.swing.JTextField();
        creditsBUSM241 = new javax.swing.JTextField();
        creditsFIN201 = new javax.swing.JTextField();
        creditsACC200 = new javax.swing.JTextField();
        creditsIS303 = new javax.swing.JTextField();
        gradeBUSM241 = new javax.swing.JComboBox();
        gradeIS100 = new javax.swing.JComboBox();
        gradeIS102 = new javax.swing.JComboBox();
        gradeIS201 = new javax.swing.JComboBox();
        gradeIS303 = new javax.swing.JComboBox();
        gradeACC200 = new javax.swing.JComboBox();
        gradeFIN201 = new javax.swing.JComboBox();
        lblCourse = new javax.swing.JLabel();
        lblCredits = new javax.swing.JLabel();
        lblGrade = new javax.swing.JLabel();
        btnCalcGPA = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        pnlGPA = new javax.swing.JPanel();
        lblGPATitle = new javax.swing.JLabel();
        lblGPA = new javax.swing.JLabel();
        pnlRed = new javax.swing.JPanel();
        pnlGreen = new javax.swing.JPanel();
        pnlYellow = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(51, 153, 255));
        pnlHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("IS Pre-Req GPA Calculator");
        lblTitle.setToolTipText("");
        pnlHeader.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 60));

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Enter Your Name:");
        pnlHeader.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 120, 30));
        pnlHeader.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 140, 30));

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 120));

        pnlGrades.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlGrades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEnterGrades.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblEnterGrades.setText("Enter Grades");
        pnlGrades.add(lblEnterGrades, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        labelIS100.setText("IS 100");
        pnlGrades.add(labelIS100, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        labelIS102.setText("IS 102");
        pnlGrades.add(labelIS102, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        labelIS201.setText("IS 201");
        pnlGrades.add(labelIS201, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        labelIS303.setText("IS 303");
        pnlGrades.add(labelIS303, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        labelACC200.setText("ACC 200");
        pnlGrades.add(labelACC200, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        labelFIN201.setText("FIN 201");
        pnlGrades.add(labelFIN201, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        labelBUSM241.setText("BUSM 241");
        pnlGrades.add(labelBUSM241, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        creditsIS201.setText("3");
        creditsIS201.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsIS201ActionPerformed(evt);
            }
        });
        pnlGrades.add(creditsIS201, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 30, -1));

        creditsIS100.setText(".5");
        pnlGrades.add(creditsIS100, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 30, -1));

        creditsIS102.setText(".5");
        pnlGrades.add(creditsIS102, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 30, -1));

        creditsBUSM241.setText("3");
        creditsBUSM241.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsBUSM241ActionPerformed(evt);
            }
        });
        pnlGrades.add(creditsBUSM241, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 30, -1));

        creditsFIN201.setText("3");
        creditsFIN201.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsFIN201ActionPerformed(evt);
            }
        });
        pnlGrades.add(creditsFIN201, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 30, -1));

        creditsACC200.setText("3");
        creditsACC200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsACC200ActionPerformed(evt);
            }
        });
        pnlGrades.add(creditsACC200, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 30, -1));

        creditsIS303.setText("3");
        creditsIS303.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsIS303ActionPerformed(evt);
            }
        });
        pnlGrades.add(creditsIS303, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 30, -1));

        gradeBUSM241.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        pnlGrades.add(gradeBUSM241, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 60, -1));

        gradeIS100.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        pnlGrades.add(gradeIS100, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 60, -1));

        gradeIS102.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        pnlGrades.add(gradeIS102, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 60, -1));

        gradeIS201.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        pnlGrades.add(gradeIS201, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 60, -1));

        gradeIS303.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        pnlGrades.add(gradeIS303, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 60, -1));

        gradeACC200.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        pnlGrades.add(gradeACC200, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 60, -1));

        gradeFIN201.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        pnlGrades.add(gradeFIN201, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 60, -1));

        lblCourse.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblCourse.setText("Course");
        pnlGrades.add(lblCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        lblCredits.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblCredits.setText("Credits");
        pnlGrades.add(lblCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        lblGrade.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblGrade.setText("Grade");
        pnlGrades.add(lblGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        btnCalcGPA.setText("Calc GPA");
        btnCalcGPA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcGPAMouseClicked(evt);
            }
        });
        pnlGrades.add(btnCalcGPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 100, 30));

        btnReset.setText("Reset");
        btnReset.setToolTipText("");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        pnlGrades.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, 30));

        getContentPane().add(pnlGrades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 280, 380));

        pnlGPA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlGPA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGPATitle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblGPATitle.setText("GPA");
        pnlGPA.add(lblGPATitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        lblGPA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pnlGPA.add(lblGPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        pnlRed.setBackground(new java.awt.Color(255, 0, 0));
        pnlRed.setVisible(false);

        javax.swing.GroupLayout pnlRedLayout = new javax.swing.GroupLayout(pnlRed);
        pnlRed.setLayout(pnlRedLayout);
        pnlRedLayout.setHorizontalGroup(
            pnlRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlRedLayout.setVerticalGroup(
            pnlRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlGPA.add(pnlRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 50, 50));

        pnlGreen.setBackground(new java.awt.Color(0, 153, 0));
        pnlGreen.setVisible(false);

        javax.swing.GroupLayout pnlGreenLayout = new javax.swing.GroupLayout(pnlGreen);
        pnlGreen.setLayout(pnlGreenLayout);
        pnlGreenLayout.setHorizontalGroup(
            pnlGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlGreenLayout.setVerticalGroup(
            pnlGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlGPA.add(pnlGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, 50));

        pnlYellow.setBackground(new java.awt.Color(255, 204, 0));
        pnlYellow.setVisible(false);

        javax.swing.GroupLayout pnlYellowLayout = new javax.swing.GroupLayout(pnlYellow);
        pnlYellow.setLayout(pnlYellowLayout);
        pnlYellowLayout.setHorizontalGroup(
            pnlYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlYellowLayout.setVerticalGroup(
            pnlYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlGPA.add(pnlYellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 50, 50));

        getContentPane().add(pnlGPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 250, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creditsIS201ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsIS201ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditsIS201ActionPerformed

    private void creditsBUSM241ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsBUSM241ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditsBUSM241ActionPerformed

    private void creditsFIN201ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsFIN201ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditsFIN201ActionPerformed

    private void creditsACC200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsACC200ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditsACC200ActionPerformed

    private void creditsIS303ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsIS303ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditsIS303ActionPerformed

    private void btnCalcGPAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcGPAMouseClicked
        
        // Get the weighted score for each course
        double is100Weighted = calcGPA( gradeIS100, creditsIS100 );
        double is102Weighted = calcGPA( gradeIS102, creditsIS102 );
        double is201Weighted = calcGPA( gradeIS201, creditsIS201 );
        double is303Weighted = calcGPA( gradeIS303, creditsIS303 );
        double acc200Weighted = calcGPA( gradeACC200, creditsACC200 );
        double fin201Weighted = calcGPA( gradeFIN201, creditsFIN201 );
        double busm241Weighted = calcGPA( gradeBUSM241, creditsBUSM241 );
        
        // Calculate the total number of credits
        double totalCredits = Double.parseDouble(creditsIS100.getText()) +
                                Double.parseDouble(creditsIS102.getText()) +
                                Double.parseDouble(creditsIS201.getText()) +
                                Double.parseDouble(creditsIS303.getText()) +
                                Double.parseDouble(creditsACC200.getText()) +
                                Double.parseDouble(creditsFIN201.getText()) +
                                Double.parseDouble(creditsBUSM241.getText());
        
        // Add up all the weighted averages
        double totalGradePoints = is100Weighted + is102Weighted + is201Weighted
                + is303Weighted + acc200Weighted + fin201Weighted + busm241Weighted;
        
        // Calculate the GPA
        double GPA = totalGradePoints / totalCredits;
        
        // Set the text of the GPA label (Format X.XX)
        lblGPA.setText(decimalFormat.format(GPA));
        
        
        // Control which "stoplight" appears
        if ( GPA >= 3.7 ) {
            pnlGreen.setVisible(true);
            pnlYellow.setVisible(false);
            pnlRed.setVisible(false);
        } else if ( GPA >= 3.2 ) {
            pnlGreen.setVisible(false);
            pnlYellow.setVisible(true);
            pnlRed.setVisible(false);
        } else {
            pnlGreen.setVisible(false);
            pnlYellow.setVisible(false);
            pnlRed.setVisible(true);
        }
    }//GEN-LAST:event_btnCalcGPAMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // Reset Name field
        txtName.setText("");
        
        // Reset GPA field
        lblGPA.setText("0.00");
        
        // Hide traffic light panels
        pnlGreen.setVisible(false);
        pnlYellow.setVisible(false);
        pnlRed.setVisible(false);
        
        // Set all course grades to A
        gradeIS100.setSelectedIndex(0);
        gradeIS102.setSelectedIndex(0);
        gradeIS201.setSelectedIndex(0);
        gradeIS303.setSelectedIndex(0);
        gradeACC200.setSelectedIndex(0);
        gradeFIN201.setSelectedIndex(0);
        gradeBUSM241.setSelectedIndex(0);
        
        // Set cursor in name field
        txtName.requestFocus();
    }//GEN-LAST:event_btnResetMouseClicked

    /**
     * calcGPA()
     * 
     * @description Converts a letter grade and number of credits into a weighted score
     *              from form inputs.
     * 
     * @param grade : Combo box containing a letter grade between A and E
     * @param numCredits : Text field containing a number value
     * @return Weighted grade as double.
     */
    private double calcGPA(javax.swing.JComboBox grade, javax.swing.JTextField numCredits)
    {
        String letterGrade = String.valueOf(grade.getSelectedItem());
        double credits = Double.parseDouble(numCredits.getText());
        
        double gradePoints = convertLetterGrade(letterGrade);
        
        return gradePoints * credits;
    }
    
    /**
     * convertLetterGrade()
     * 
     * @description Converts a letter grade to its corresponding value on a 4
     *              point scale
     * 
     * @param grade : Letter grade between A and E to be converted
     * @return Grade points on a 4.0 scale as a double
     */
    private double convertLetterGrade(String grade)
    {
        double gradePoint;
        
        switch (grade)
        {
            case "A"  : gradePoint = 4.0; break;
            case "A-" : gradePoint = 3.7; break;
            case "B+" : gradePoint = 3.4; break;
            case "B"  : gradePoint = 3.0; break;
            case "B-" : gradePoint = 2.7; break;
            case "C+" : gradePoint = 2.4; break;
            case "C"  : gradePoint = 2.0; break;
            case "C-" : gradePoint = 1.7; break;
            case "D+" : gradePoint = 1.4; break;
            case "D"  : gradePoint = 1.0; break;
            case "D-" : gradePoint = 0.7; break;
            case "E"  : gradePoint = 0.0; break;
            default   : gradePoint = 0.0;
        }
        
        return gradePoint;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcGPA;
    private javax.swing.JButton btnReset;
    private javax.swing.JTextField creditsACC200;
    private javax.swing.JTextField creditsBUSM241;
    private javax.swing.JTextField creditsFIN201;
    private javax.swing.JTextField creditsIS100;
    private javax.swing.JTextField creditsIS102;
    private javax.swing.JTextField creditsIS201;
    private javax.swing.JTextField creditsIS303;
    private javax.swing.JComboBox gradeACC200;
    private javax.swing.JComboBox gradeBUSM241;
    private javax.swing.JComboBox gradeFIN201;
    private javax.swing.JComboBox gradeIS100;
    private javax.swing.JComboBox gradeIS102;
    private javax.swing.JComboBox gradeIS201;
    private javax.swing.JComboBox gradeIS303;
    private javax.swing.JLabel labelACC200;
    private javax.swing.JLabel labelBUSM241;
    private javax.swing.JLabel labelFIN201;
    private javax.swing.JLabel labelIS100;
    private javax.swing.JLabel labelIS102;
    private javax.swing.JLabel labelIS201;
    private javax.swing.JLabel labelIS303;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblEnterGrades;
    private javax.swing.JLabel lblGPA;
    private javax.swing.JLabel lblGPATitle;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlGPA;
    private javax.swing.JPanel pnlGrades;
    private javax.swing.JPanel pnlGreen;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlRed;
    private javax.swing.JPanel pnlYellow;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
