/*
 * Author      : Andy Mockler
 * Date        : March 6, 2015
 * Description : IS 303 Homework 6. Simple NetBeans GUI app that tests if
 *               two names score well with the TRUELOVE™ scale.
 */

/**
 *
 * @author Andy Mockler
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBody = new javax.swing.JPanel();
        lblTheirName = new javax.swing.JLabel();
        txtTheirName = new javax.swing.JTextField();
        btnTestTrueLove = new javax.swing.JButton();
        lblYourName = new javax.swing.JLabel();
        txtYourName = new javax.swing.JTextField();
        lblResult = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("True Love Calculator");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTheirName.setLabelFor(txtTheirName);
        lblTheirName.setText("Their Name");
        pnlBody.add(lblTheirName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        txtTheirName.setToolTipText("First Name");
        txtTheirName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTheirNameActionPerformed(evt);
            }
        });
        pnlBody.add(txtTheirName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 370, -1));

        btnTestTrueLove.setText("Is It True Love?");
        btnTestTrueLove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTestTrueLoveMouseClicked(evt);
            }
        });
        btnTestTrueLove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestTrueLoveActionPerformed(evt);
            }
        });
        pnlBody.add(btnTestTrueLove, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 370, -1));

        lblYourName.setLabelFor(txtYourName);
        lblYourName.setText("Your Name");
        pnlBody.add(lblYourName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        txtYourName.setToolTipText("First Name");
        txtYourName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYourNameActionPerformed(evt);
            }
        });
        pnlBody.add(txtYourName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 370, -1));

        lblResult.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlBody.add(lblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 380, 40));

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        jLabel1.setText("True Love");
        pnlBody.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 60));

        btnClose.setText("Close");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        pnlBody.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        getContentPane().add(pnlBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTheirNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTheirNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTheirNameActionPerformed

    private void btnTestTrueLoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestTrueLoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTestTrueLoveActionPerformed

    private void txtYourNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYourNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYourNameActionPerformed
    
    private void btnTestTrueLoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTestTrueLoveMouseClicked
        // Start a counter for TRUELOVE
        int trueLoveCounter = 0;
        
        // Get Values from Text Boxes
        String yourName = txtYourName.getText();
        String theirName = txtTheirName.getText();
        
        // Combine names and clean spaces for efficiency
        String names = yourName + theirName;
        names = names.replace(" ", "");
        
        // Call the name length once instead of on each loop
        int nameLength = names.length();
        for ( int i = 0; i < nameLength; i++ )
        {
            // Get one letter of the names
            String currentLetter = names.substring(i, i+1);
            
            // Check if it has TRULOV and add 1 if it does
            // If it is an E, add 2
            if  ( 
                    currentLetter.equalsIgnoreCase("T") ||
                    currentLetter.equalsIgnoreCase("R") ||
                    currentLetter.equalsIgnoreCase("U") ||
                    currentLetter.equalsIgnoreCase("L") ||
                    currentLetter.equalsIgnoreCase("O") ||
                    currentLetter.equalsIgnoreCase("V")
                )
                trueLoveCounter += 1;
            else if ( currentLetter.equalsIgnoreCase("E") )
                trueLoveCounter += 2;
        }
        
        // Check Results
        if (trueLoveCounter >= 10)
            lblResult.setText("You Found a Match!");
        else
            lblResult.setText("Go join a convent!");
    }//GEN-LAST:event_btnTestTrueLoveMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // Exit on "close" click
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {    
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnTestTrueLove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTheirName;
    private javax.swing.JLabel lblYourName;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JTextField txtTheirName;
    private javax.swing.JTextField txtYourName;
    // End of variables declaration//GEN-END:variables
}
